apiVersion: apps/v1
kind: Deployment
metadata:
    name: short-url-backend
    labels:
        app: short-url-backend
spec:
    replicas: 1
    selector:
        matchLabels:
            app: short-url-backend
    template:
        metadata:
            labels:
                app: short-url-backend
        spec:
            containers:
                - name: short-url-backend
                  image: abacus1234/short-url-backend:latest
                  imagePullPolicy: IfNotPresent
                  ports:
                      - containerPort: 3000
                  env:
                      - name: NODE_ENV
                        value: "production"
                      - name: PORT
                        value: "3000"
                  resources:
                      requests:
                          memory: "128Mi"
                          cpu: "100m"
                      limits:
                          memory: "512Mi"
                          cpu: "500m"
                  startupProbe:
                      httpGet:
                          path: /stats/url/1
                          port: 3000
                      initialDelaySeconds: 60
                      periodSeconds: 10
                      failureThreshold: 30
                      timeoutSeconds: 5
                  livenessProbe:
                      httpGet:
                          path: /stats/url/1
                          port: 3000
                      initialDelaySeconds: 90
                      periodSeconds: 10
                      timeoutSeconds: 5
                  readinessProbe:
                      httpGet:
                          path: /stats/url/1
                          port: 3000
                      initialDelaySeconds: 65
                      periodSeconds: 5
                      timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
    name: short-url-service
spec:
    selector:
        app: short-url-backend
    ports:
        - protocol: TCP
          port: 80
          targetPort: 3000
          nodePort: 30080
    type: NodePort
